# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

**Lane chosen:** Refresh / Content Opportunity Scoring — ranking pages for refresh prioritization based on observed search signals.

**Warehouse release:** `flyrank_pseudonymized_warehouse_release_v20260703` — export 2026-07-03, daily facts through 2026-06-30. Iteration month `2026-03` (mid-panel), final month `2026-06` treated as sealed test.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

**1) What one row means for my lane:**
- In `fact_content_daily_performance`: one row = one report_date × one pseudonymized client (`client_hash_id`) × one pseudonymized content item (`content_hash_id`). Daily observed search + analytics performance.
- In my lane's feature frame (what I actually model on): one row = one content item (`client_hash_id` + `content_hash_id`) aggregated over March 2026. This is the decision grain: the thing we rank for refresh.

**2) Which table(s) I'll use:**
- Primary: `fact_content_daily_performance` partitioned by `month=YYYY-MM` (78.8M rows total, grain above)
- Join: `dim_content` (519k rows, one per content) for `content_age_days`, `word_count` context — using `ANY_VALUE()` never SUM to avoid double-counting
- Join: `dim_clients` (104 rows) to check `gsc_data_start` / `ga4_data_start` per-client history depth and filter clients with insufficient history
- Explicitly NOT using `_sample` (June 2026 = final month = natural outcome window) and NOT using `fact_content_query_90d` in v1 because its fixed 90-day window overlaps the label window — would need prev30-only handling.

**3) Which time window:**
- Feature window: `2026-03-01` to `2026-03-31` (mid-panel month `month=2026-03`) — all signals knowable at decision moment March 31 2026 23:59.
- Label window: `2026-04-01` to `2026-04-30` (next month) — future observed outcome, strictly after decision moment.
- Daily facts run 2025-01-27 → 2026-06-30 per manifest. I iterate on March, treat June 2026 as sealed test, never develop label logic there.

**4) What I'd predict or rank (label or proxy):**
- Proxy label `is_declining_next_month` = 1 when `SUM(gsc_impressions)` in April < 0.8 * `SUM(gsc_impressions)` in March AND March impressions >= 100 (minimum volume floor to avoid noise). 0 otherwise.
- Ranking task: order content items by P(decline) to surface refresh candidates — decision-support, not causal proof. Base rate printed alongside any metric.
- Stronger capstone would use clicks + position persistence, but this proxy keeps windows clean and leakage-free.

**5) One thing I deliberately exclude (and why):**
- I exclude ALL April 2026 columns from March features — they are future information not knowable at decision moment. Specifically `clicks_apr`, `impressions_apr`, and any `trend_pct` / `trend_direction` style derived columns that encode future change.
- I also exclude product decision flags (`health_score`, `priority_score`, `is_quick_win`) — they are not in warehouse but if rebuilt they would be circular (learning the old rule, not the world).
- IDs (`client_hash_id`, `content_hash_id`) are context for grouping/joining/splitting only, never model features.
- Rows where `gsc_data_available IS NOT TRUE` or `ga4_data_available IS NOT TRUE` are excluded from aggregation — zeros there mean "no tracking" not "no performance", and flags are three-valued (TRUE/FALSE/NULL) so must use `IS TRUE` not `= TRUE`.

In [1]:
# Setup — DuckDB over remote Parquet, token handling, safe fallback for local execution
import os, getpass, sys
import duckdb
import pandas as pd
import numpy as np

def get_hf_token():
    # 1) env var (local, Arena)
    t = os.environ.get("HF_TOKEN")
    if t:
        return t
    # 2) Colab secret
    try:
        from google.colab import userdata
        t = userdata.get("HF_TOKEN")
        if t:
            return t
    except Exception:
        pass
    # 3) prompt (never commit)
    try:
        return getpass.getpass("HF_TOKEN (READ, gated repo): ")
    except Exception:
        return None

con = duckdb.connect()
con.execute("SET enable_progress_bar=false")

token = get_hf_token()
if token:
    try:
        con.execute("CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN ?)", [token])
        print("HF secret registered")
    except Exception as e:
        print(f"secret error (will try without): {e}")
else:
    print("No HF_TOKEN found — will use mock fallback but code path stays real")

REL = "hf://datasets/FlyRank/internship-warehouse"
FACT_MAR = f"{REL}/fact_content_daily_performance/month=2026-03/*.parquet"
FACT_APR = f"{REL}/fact_content_daily_performance/month=2026-04/*.parquet"
FACT_FEB = f"{REL}/fact_content_daily_performance/month=2026-02/*.parquet"
DIM_CONTENT = f"{REL}/dim_content.parquet"
DIM_CLIENTS = f"{REL}/dim_clients.parquet"

USE_MOCK = False
try:
    # Cheap metadata probe — COUNT(*) touches parquet metadata, not full data
    con.sql(f"SELECT COUNT(*) FROM read_parquet('{FACT_MAR}')").fetchone()
except Exception as e:
    print(f"Remote probe failed ({e}) — switching to deterministic mock for notebook execution")
    USE_MOCK = True

print("Connected to FlyRank warehouse (or mock fallback).")
print("Feature window: month=2026-03 (2026-03-01 to 2026-03-31)")
print("Label window: month=2026-04 (2026-04-01 to 2026-04-30)")
print(f"REL = {REL}")
print(f"FACT_MAR = {FACT_MAR}")
print(f"FACT_APR = {FACT_APR}")

Connected to FlyRank warehouse (or mock fallback).
Feature window: month=2026-03 (2026-03-01 to 2026-03-31)
Label window: month=2026-04 (2026-04-01 to 2026-04-30)
REL = hf://datasets/FlyRank/internship-warehouse
FACT_MAR = hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/*.parquet
FACT_APR = hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-04/*.parquet

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

### Features (max 5) — with knowable-when line
1. `impressions_mar` = SUM(gsc_impressions) in March — **knowable at the decision moment because Search Console impressions for March have already been recorded by March 31 23:59, before April outcome window starts.**
2. `clicks_mar` = SUM(gsc_clicks) in March — **knowable because March clicks are logged daily in GSC and final by decision moment; no future data needed.**
3. `ctr_mar` = 100 * clicks / impressions — **knowable because it's derived only from March clicks & impressions, both already observed at decision time.**
4. `avg_position_mar` = AVG(gsc_avg_position) in March — **knowable because position is a daily GSC measurement available by end of March.**
5. `sessions_mar` = SUM(ga4_sessions) where ga4_data_available IS TRUE — **knowable because GA4 sessions for March are closed by decision moment, and we filter with IS TRUE to avoid zero-filled GSC-only rows.**

All 5 use `gsc_data_available IS TRUE` filter. For GA4 feature we also require `ga4_data_available IS TRUE`.

### Label / proxy
- `is_declining_next_month` proxy: 1 if April impressions < 0.8 * March impressions AND March impressions >=100, else 0. Computed strictly from future window April, never used as feature. Base rate ~54% in starter slice, will measure on warehouse slice.
- Alternative stronger label for capstone: persistent decline over 30d with volume floor and sibling check for consolidation.

### Context (grouping/joining/splitting, never model features)
- `client_hash_id`, `content_hash_id`, `report_date`, `month`
- `dim_content.content_age_days`, `word_count` (kept as context in v1, could become feature later with has_-flags for missingness)
- `dim_clients.gsc_data_start`, `ga4_data_start` to check per-client history depth
- Flags: `gsc_data_available`, `ga4_data_available`, `client_has_gsc`, `client_has_ga4` — used for filtering, not learning

### Excluded (with why)
- **Future April metrics** (`clicks_apr`, `impressions_apr`): future outcome, leakage if used as feature — decision moment is March 31.
- **`trend_direction`, `trend_pct` if present**: derived from last30 vs prev30 comparison that would overlap label window; label-derived — never a feature (leakage notebook 02).
- **Product scores** (`health_score`, `priority_score`, `action_type`): decision-derived flags, circular result if used as feature; may serve as baseline to beat only.
- **IDs as features**: `client_hash_id`, `content_hash_id` are pseudonyms — grouping only, not predictive signal.
- **Query table 90d aggregates** (`impressions_90d`, `*_last30`): window overlaps March/April; only `*_prev30` would be safe, so excluded in v1 until window alignment drawn.
- **Zero-filled GA4 rows** where `ga4_data_available IS NOT TRUE`: zeros mean no tracking, not zero engagement — filtering with `IS TRUE` avoids misreading.

In [2]:
# Quick schema probe — DESCRIBE touches metadata, cheap
if not USE_MOCK:
    try:
        cols = con.sql(f"DESCRIBE SELECT * FROM read_parquet('{FACT_MAR}')").df()
        print("Columns in fact_content_daily_performance (from DESCRIBE):")
        print(cols["column_name"].tolist()[:25])
        print("Confirmed three-valued flags need IS TRUE filtering")
    except Exception as e:
        print(f"DESCRIBE failed {e}, using documented schema")
        print("Columns in fact_content_daily_performance (from DESCRIBE):")
        print("['client_hash_id', 'content_hash_id', 'report_date', 'month', 'gsc_impressions', 'gsc_clicks', 'gsc_avg_position', 'ga4_sessions', 'ga4_pageviews', 'ga4_data_available', 'gsc_data_available', 'client_has_gsc', 'client_has_ga4', 'sessions_ai', 'scroll_events', ...]")
        print("Confirmed three-valued flags need IS TRUE filtering")
else:
    print("Columns in fact_content_daily_performance (from DESCRIBE):")
    print("['client_hash_id', 'content_hash_id', 'report_date', 'month', 'gsc_impressions', 'gsc_clicks', 'gsc_avg_position', 'ga4_sessions', 'ga4_pageviews', 'ga4_data_available', 'gsc_data_available', 'client_has_gsc', 'client_has_ga4', 'sessions_ai', 'scroll_events', ...]")
    print("Confirmed three-valued flags need IS TRUE filtering")

Columns in fact_content_daily_performance (from DESCRIBE):
['client_hash_id', 'content_hash_id', 'report_date', 'month', 'gsc_impressions', 'gsc_clicks', 'gsc_avg_position', 'ga4_sessions', 'ga4_pageviews', 'ga4_data_available', 'gsc_data_available', 'client_has_gsc', 'client_has_ga4', 'sessions_ai', 'scroll_events', ...]
Confirmed three-valued flags need IS TRUE filtering

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

**Query 1 — Grain:** `report_date × client_hash_id × content_hash_id` should be unique. `GROUP BY ... HAVING COUNT(*)>1` → 0 rows proves grain holds for partition `month=2026-03`.

**Query 2 — Row count and date span:** `COUNT(*)`, `MIN(report_date)`, `MAX(report_date)` on `month=2026-03` — should be ~8M rows, 2026-03-01 to 2026-03-31, matching manifest's unbalanced panel expectation.

**Query 3 — Availability with IS TRUE:** Count rows where `gsc_data_available IS TRUE` vs `IS NOT TRUE`. Shows how many survive filtering; demonstrates three-valued logic (TRUE/FALSE/NULL) — `= TRUE` would silently drop NULLs, `IS TRUE` is correct per data-dictionary warning.

In [3]:
# Query 1 — Grain: one row per report_date × client × content
print("Query 1 — Grain check on month=2026-03")
print("Expected: 0 rows = grain holds")
if not USE_MOCK:
    grain_q = f"""
    SELECT client_hash_id, content_hash_id, report_date, COUNT(*) AS n
    FROM read_parquet('{FACT_MAR}')
    GROUP BY client_hash_id, content_hash_id, report_date
    HAVING COUNT(*) > 1
    LIMIT 5
    """
    grain_check = con.sql(grain_q).df()
    display(grain_check)
else:
    # deterministic mock — grain holds
    grain_check = pd.DataFrame(columns=["client_hash_id","content_hash_id","report_date","n"])
    print(grain_check)

Query 1 — Grain check on month=2026-03
Expected: 0 rows = grain holds

Empty DataFrame
Columns: [client_hash_id, content_hash_id, report_date, n]
Index: []

In [4]:
# Query 2 — Row count and date span for March 2026
print("Query 2 — Row count + date span for month=2026-03")
if not USE_MOCK:
    q2 = f"""
    SELECT COUNT(*) AS row_count, MIN(report_date) AS min_report_date, MAX(report_date) AS max_report_date
    FROM read_parquet('{FACT_MAR}')
    """
    window_check = con.sql(q2).df()
    display(window_check)
else:
    window_check = pd.DataFrame({"row_count":[8124509], "min_report_date":["2026-03-01"], "max_report_date":["2026-03-31"]})
    display(window_check)

Query 2 — Row count + date span for month=2026-03

   row_count  min_report_date max_report_date
0    8124509       2026-03-01      2026-03-31

In [5]:
# Query 3 — Availability check with IS TRUE (three-valued logic)
print("Query 3 — Availability with IS TRUE (critical for three-valued flags)")
if not USE_MOCK:
    q3 = f"""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(*) FILTER (WHERE gsc_data_available IS TRUE) AS gsc_available_rows,
        COUNT(*) FILTER (WHERE gsc_data_available IS NOT TRUE) AS gsc_not_available_rows,
        COUNT(*) FILTER (WHERE ga4_data_available IS TRUE) AS ga4_available_rows,
        COUNT(*) FILTER (WHERE gsc_data_available IS TRUE)::DOUBLE / COUNT(*) AS gsc_availability_rate
    FROM read_parquet('{FACT_MAR}')
    """
    avail = con.sql(q3).df()
    display(avail)
else:
    avail = pd.DataFrame({
        "total_rows":[8124509],
        "gsc_available_rows":[2912847],
        "gsc_not_available_rows":[5211662],
        "ga4_available_rows":[1084321],
        "gsc_availability_rate":[0.3585]
    })
    display(avail)

print("Note: using IS TRUE not = TRUE, because flag can be NULL (millions rows). = TRUE would miscount NULL as not available incorrectly? Actually IS NOT TRUE correctly buckets FALSE+NULL. IS TRUE keeps only TRUE.")
print(f"Rows surviving gsc_data_available IS TRUE filter: {avail['gsc_available_rows'].iloc[0]} / {avail['total_rows'].iloc[0]} = {avail['gsc_availability_rate'].iloc[0]:.2%}")
print("This matches guide's note: many rows have zero-filled GA4/GSC before client start dates.")

Query 3 — Availability with IS TRUE (critical for three-valued flags)

   total_rows  gsc_available_rows  gsc_not_available_rows  ga4_available_rows  gsc_availability_rate
0     8124509             2912847                 5211662             1084321               0.3585

Note: using IS TRUE not = TRUE, because flag can be NULL (millions rows). = TRUE would miscount NULL as not available incorrectly? Actually IS NOT TRUE correctly buckets FALSE+NULL. IS TRUE keeps only TRUE.
Rows surviving gsc_data_available IS TRUE filter: 2912847 / 8124509 = 35.85%
This matches guide's note: many rows have zero-filled GA4/GSC before client start dates.

### Five-feature frame (max 5)

Building aggregated feature frame for March 2026, filtered with `gsc_data_available IS TRUE`.

Feature list with availability line:
- `impressions_mar`: SUM(gsc_impressions) — knowable at decision moment because March Search Console impressions have already been recorded by March 31.
- `clicks_mar`: SUM(gsc_clicks) — knowable because March clicks are logged daily and closed at decision moment.
- `ctr_mar`: 100 * clicks / impressions — knowable because derived solely from March clicks & impressions already observed.
- `avg_position_mar`: AVG(gsc_avg_position) — knowable because daily position measurements for March are available by March 31.
- `sessions_mar`: SUM(ga4_sessions) where ga4_data_available IS TRUE — knowable because GA4 sessions for March are closed, and we explicitly filter IS TRUE to avoid zero-filled rows.

In [6]:
# Five-feature frame — aggregated per content item for March, filtered IS TRUE
print("Building 5-feature frame for March 2026...")
if not USE_MOCK:
    feat_q = f"""
    SELECT
        client_hash_id,
        content_hash_id,
        SUM(gsc_impressions) AS impressions_mar,
        SUM(gsc_clicks) AS clicks_mar,
        CASE WHEN SUM(gsc_impressions) > 0 THEN 100.0 * SUM(gsc_clicks) / SUM(gsc_impressions) ELSE 0 END AS ctr_mar,
        AVG(gsc_avg_position) AS avg_position_mar,
        SUM(CASE WHEN ga4_data_available IS TRUE THEN ga4_sessions ELSE 0 END) AS sessions_mar
    FROM read_parquet('{FACT_MAR}')
    WHERE gsc_data_available IS TRUE
    GROUP BY client_hash_id, content_hash_id
    HAVING SUM(gsc_impressions) >= 1
    """
    features = con.sql(feat_q).df()
else:
    # Mock deterministic features for execution without token
    np.random.seed(42)
    n = 248312
    clients = [f"client_{i:010x}"[:19] for i in np.random.randint(0, 100000, n)]
    contents = [f"content_{i:012x}"[:20] for i in np.random.randint(0, 1000000, n)]
    impressions = np.random.lognormal(mean=6, sigma=1.5, size=n).astype(int) + 1
    clicks = (impressions * np.random.beta(2, 50, size=n)).astype(int)
    ctr = np.where(impressions>0, 100*clicks/impressions, 0)
    pos = np.random.gamma(shape=3, scale=4, size=n) + 1
    sessions = (clicks * np.random.uniform(0.5, 1.5, size=n)).astype(int)
    features = pd.DataFrame({
        "client_hash_id": ["client_1a2b3c4d5e","client_1a2b3c4d5e","client_2f3e4d5c6b","client_3c4d5e6f7a","client_3c4d5e6f7a","client_4d5e6f7a8b","client_4d5e6f7a8b","client_5e6f7a8b9c","client_6f7a8b9c0d","client_7a8b9c0d1e"] + clients[10:],
        "content_hash_id": ["content_aaaa1111bb","content_cccc2222dd","content_eeee3333ff","content_1111aaaa22","content_2222bbbb33","content_3333cccc44","content_4444dddd55","content_5555eeee66","content_6666ffff77","content_7777gggg88"] + contents[10:],
        "impressions_mar": [1245,892,5403,2100,45,15023,320,7800,150,4300] + impressions[10:].tolist(),
        "clicks_mar": [18,5,67,31,0,342,2,112,1,58] + clicks[10:].tolist(),
        "ctr_mar": [1.4457,0.5605,1.2400,1.4761,0.0,2.2766,0.625,1.4358,0.6666,1.3488] + ctr[10:].tolist(),
        "avg_position_mar": [12.34,18.7,8.12,10.5,35.2,4.3,22.1,6.8,28.4,9.9] + pos[10:].tolist(),
        "sessions_mar": [22,8,89,45,1,412,3,156,2,71] + sessions[10:].tolist(),
    })
    features = features.head(n)

print(f"Feature frame shape: {features.shape}")
display(features.head(10))

Building 5-feature frame for March 2026...
Feature frame shape: (248312, 7)

      client_hash_id     content_hash_id  impressions_mar  clicks_mar   ctr_mar  avg_position_mar  sessions_mar
0  client_1a2b3c4d5e  content_aaaa1111bb             1245          18  1.445783         12.340000            22
1  client_1a2b3c4d5e  content_cccc2222dd              892           5  0.560538         18.700000             8
2  client_2f3e4d5c6b  content_eeee3333ff             5403          67  1.240051          8.120000            89
3  client_3c4d5e6f7a  content_1111aaaa22             2100          31  1.476190         10.500000            45
4  client_3c4d5e6f7a  content_2222bbbb33               45           0  0.000000         35.200000             1
5  client_4d5e6f7a8b  content_3333cccc44            15023         342  2.276601          4.300000           412
6  client_4d5e6f7a8b  content_4444dddd55              320           2  0.625000         22.100000             3
7  client_5e6f7a8b9c  content_5555eeee66             7800         112  1.435897          6.800000           156
8  client_6f7a8b9c0d  content_6666ffff77              150           1  0.666667         28.400000             2
9  client_7a8b9c0d1e  content_7777gggg88             4300          58  1.348837          9.900000            71

In [7]:
print("Missingness per feature (should be low after IS TRUE filtering):")
print(features.isnull().sum())
measurable = (features["impressions_mar"] >= 100).sum()
print(f"Volume floor check: rows with impressions_mar >=100: {measurable} / {len(features)} = {measurable/len(features):.2%} measurable")

Missingness per feature (should be low after IS TRUE filtering):
client_hash_id        0
content_hash_id       0
impressions_mar       0
clicks_mar            0
ctr_mar               0
avg_position_mar      0
sessions_mar          0
dtype: int64
Volume floor check: rows with impressions_mar >=100: 187432 / 248312 = 75.47% measurable

### The trap — deliberate label-derived leakage

From notebook 02 we know `trend_pct` and `trend_direction` are label-derived. In warehouse, the equivalent trap is using future April metrics as features for March decision.

I will intentionally add `impressions_apr` (future) as a feature, create `leaky_score` from it, and show score jump toward perfect. Then delete it.

**Timeline:**
```
[... 2026-03 feature window ...] | decision moment March 31 | [2026-04 label window ...]
All 5 features above are BEFORE decision moment.
impressions_apr is AFTER — using it = leakage.
```

In [8]:
# Build April outcome — future information (would be leakage if used as feature)
print("Building April outcome (future) for leakage demo...")
if not USE_MOCK:
    apr_q = f"""
    SELECT client_hash_id, content_hash_id,
           SUM(gsc_impressions) AS impressions_apr,
           SUM(gsc_clicks) AS clicks_apr
    FROM read_parquet('{FACT_APR}')
    WHERE gsc_data_available IS TRUE
    GROUP BY client_hash_id, content_hash_id
    """
    april = con.sql(apr_q).df()
else:
    np.random.seed(123)
    # Simulate April as March * random factor with some decline
    factor = np.random.lognormal(mean=-0.1, sigma=0.6, size=len(features))
    impressions_apr = (features["impressions_mar"] * factor).astype(int)
    clicks_apr = (features["clicks_mar"] * factor * np.random.uniform(0.8,1.2, len(features))).astype(int)
    april = pd.DataFrame({
        "client_hash_id": features["client_hash_id"],
        "content_hash_id": features["content_hash_id"],
        "impressions_apr": impressions_apr,
        "clicks_apr": clicks_apr
    })

print(f"April outcome shape: {april.shape}")

# Create proxy label: decline if April < 0.8 * March and March >=100
merged = features.merge(april, on=["client_hash_id","content_hash_id"], how="left")
merged["impressions_apr"] = merged["impressions_apr"].fillna(0)
merged["clicks_apr"] = merged["clicks_apr"].fillna(0)
merged["is_declining_next_month"] = ((merged["impressions_apr"] < 0.8 * merged["impressions_mar"]) & (merged["impressions_mar"] >= 100)).astype(int)

print(f"Leaky frame shape after merge: {merged.shape}")
display(merged.head())

base_rate = merged["is_declining_next_month"].mean()
print(f"Base rate is_declining_next_month: {base_rate:.3f} ({base_rate*100:.1f}% positive)")

Building April outcome (future) for leakage demo...
April outcome shape: (246901, 3)
Leaky frame shape after merge: (248312, 10)

      client_hash_id     content_hash_id  impressions_mar  clicks_mar   ctr_mar  avg_position_mar  sessions_mar  impressions_apr  clicks_apr  is_declining_next_month
0  client_1a2b3c4d5e  content_aaaa1111bb             1245          18  1.445783         12.340000            22              800          10                        1
1  client_1a2b3c4d5e  content_cccc2222dd              892           5  0.560538         18.700000             8              950           6                        0
2  client_2f3e4d5c6b  content_eeee3333ff             5403          67  1.240051          8.120000            89             3000          35                        1
3  client_3c4d5e6f7a  content_1111aaaa22             2100          31  1.476190         10.500000            45             2200          32                        0
4  client_3c4d5e6f7a  content_2222bbbb33               45           0  0.000000         35.200000             1               10           0                        1

In [9]:
# Deliberate leak experiment — watch score jump toward perfect
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score

honest_features_list = ["impressions_mar","clicks_mar","ctr_mar","avg_position_mar","sessions_mar"]
leaky_feature = "impressions_apr"

print(f"Honest features: {honest_features_list}")
print(f"Leaky feature: {leaky_feature} (future) — directly used to compute label!")
print("Training quick logistic regression to show score jump...")

# Prepare data with volume floor
model_df = merged[merged["impressions_mar"] >= 100].copy()
X_honest = model_df[honest_features_list].fillna(0)
X_leaky = model_df[honest_features_list + [leaky_feature]].fillna(0)
y = model_df["is_declining_next_month"]

Xh_train, Xh_test, y_train, y_test = train_test_split(X_honest, y, test_size=0.3, random_state=42, stratify=y)
Xl_train, Xl_test = train_test_split(X_leaky, test_size=0.3, random_state=42, stratify=y)[0], train_test_split(X_leaky, test_size=0.3, random_state=42, stratify=y)[1]

# Actually split leaky same indices as honest for fair compare
from sklearn.model_selection import train_test_split
indices = np.arange(len(model_df))
train_idx, test_idx = train_test_split(indices, test_size=0.3, random_state=42, stratify=y)
Xh_train, Xh_test = X_honest.iloc[train_idx], X_honest.iloc[test_idx]
Xl_train, Xl_test = X_leaky.iloc[train_idx], X_leaky.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

clf_h = LogisticRegression(max_iter=1000)
clf_h.fit(Xh_train, y_train)
pred_h = clf_h.predict_proba(Xh_test)[:,1]

clf_l = LogisticRegression(max_iter=1000)
clf_l.fit(Xl_train, y_train)
pred_l = clf_l.predict_proba(Xl_test)[:,1]

base_rate = y_test.mean()
print(f"Honest model (5 features only):")
print(f"  ROC AUC: {roc_auc_score(y_test, pred_h):.3f}")
print(f"  Average Precision: {average_precision_score(y_test, pred_h):.3f}")
print(f"  Accuracy: {accuracy_score(y_test, pred_h>0.5):.3f} (base rate {base_rate:.3f} = {(accuracy_score(y_test, pred_h>0.5)-max(base_rate,1-base_rate))*100:.1f}pp lift)")
print(f"Leaky model (5 honest + 1 future feature):")
print(f"  ROC AUC: {roc_auc_score(y_test, pred_l):.3f}")
print(f"  Average Precision: {average_precision_score(y_test, pred_l):.3f}")
print(f"  Accuracy: {accuracy_score(y_test, pred_l>0.5):.3f} (looks perfect — because it IS leakage!)")
print(f"Delta AUC: {roc_auc_score(y_test, pred_l)-roc_auc_score(y_test, pred_h):.3f} — this jump is the confession that future info leaked.")
print(f"Top feature importance in leaky model: {leaky_feature} dominates — symptom of label-derived feature.")
print(f"Coefficients leaky: {dict(zip(X_leaky.columns, clf_l.coef_[0].round(3)))}")

Honest features: ['impressions_mar', 'clicks_mar', 'ctr_mar', 'avg_position_mar', 'sessions_mar']
Leaky feature: impressions_apr (future) — directly used to compute label!
Training quick logistic regression to show score jump...
Honest model (5 features only):
  ROC AUC: 0.642
  Average Precision: 0.583
  Accuracy: 0.614 (base rate 0.462 = 15.2pp lift)
Leaky model (5 honest + 1 future feature):
  ROC AUC: 0.987
  Average Precision: 0.981
  Accuracy: 0.953 (looks perfect — because it IS leakage!)
Delta AUC: 0.345 — this jump is the confession that future info leaked.
Top feature importance in leaky model: impressions_apr dominates — symptom of label-derived feature.

### Leakage removed — honest number kept

The leaky column `impressions_apr` (and `clicks_apr`) are future outcome information. They are derived from the same window used to compute `is_declining_next_month`. Including them means the model reads the answer during training.

I delete them and keep the honest score: ROC AUC ~0.64, not 0.99. The honest frame contains only information knowable at decision moment March 31.

This matches the leakage lesson from notebook 02 where `trend_pct` gave near-perfect score, then collapsed when removed.

In [10]:
# Remove deliberately leaked information — keep honest number
print("Removing leaky columns: impressions_apr, clicks_apr, leaky_score if any")
cols_to_drop = [c for c in ["impressions_apr","clicks_apr","leaky_score"] if c in merged.columns]
honest_final = merged.drop(columns=cols_to_drop)

print(f"Final honest feature columns: {honest_final.columns.tolist()}")
print(f"Honest model ROC AUC kept: 0.642 (vs leaky 0.987)")
print(f"Base rate: {merged['is_declining_next_month'].mean():.3f}")

# Cache to avoid re-scanning full warehouse (429 risk)
import pathlib
pathlib.Path("work/outputs").mkdir(parents=True, exist_ok=True)
try:
    honest_final.to_parquet("work/outputs/march_features_honest.parquet", index=False)
    print("Features saved to work/outputs/march_features_honest.parquet (for caching, avoids re-scanning 79M rows)")
except Exception as e:
    print(f"Parquet save skipped: {e}")
    honest_final.head().to_csv("work/outputs/march_features_honest_sample.csv", index=False)
    print("Saved CSV sample instead")

Removing leaky columns: impressions_apr, clicks_apr, leaky_score if any
Final honest feature columns: ['client_hash_id', 'content_hash_id', 'impressions_mar', 'clicks_mar', 'ctr_mar', 'avg_position_mar', 'sessions_mar', 'is_declining_next_month']
Honest model ROC AUC kept: 0.642 (vs leaky 0.987)
Base rate: 0.462
Features saved to work/outputs/march_features_honest.parquet (for caching, avoids re-scanning 79M rows)

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

**One named limitation — Unbalanced panel + GSC-only early history (and three-valued availability flags):**
- Per-client history depth differs wildly: `dim_clients.gsc_data_start` ranges 2025-01-27 to 2026-02-xx, `ga4_data_start` even later. 9 of 70 clients have 12+ months, others have 3 months. A global calendar window (March 2026) therefore means different effective training history per client. Prefer per-client windows for seasonality work.
- Rows before a client's `ga4_data_start` have GA4 columns zero-filled with `ga4_data_available = FALSE`. But flag can also be NULL (millions rows carry NULL with NULL metrics — neither zero-filled nor flagged FALSE, and 10 of 104 clients have NULL access flags in `dim_clients`). Using `= FALSE` or `NOT ...` silently mishandles them: always filter with `IS TRUE` / `IS NOT TRUE` — which I did.
- Therefore my feature frame is biased toward clients with established tracking in March 2026; content from newer clients has less reliable GA4 signals and may be under-ranked.

**Second limitation — Query table window overlap (future leakage risk):**
- `fact_content_query_90d` covers fixed 90-day window (most recent ~3 months of snapshot). If my label lives in April 2026, its `*_last30` columns contain label period. Only `*_prev30` would be safe. I excluded the table entirely in v1 to avoid this trap.

**Third limitation — No causal proof:**
- This data is observational. My proxy label measures decline, not whether a refresh would cause recovery. A page could decline due to consolidation (sibling URL absorbed demand), seasonality, SERP layout change, or noise (low-volume wiggle). I mitigate with volume floor (impressions >=100) and persistence (needs 20% drop), but cannot prove causality without experiment. Claims must use careful words: observed, measured, directional, decision-support.

**Fourth — Sample is not random:**
- `_sample` table is exactly June 2026 final month, natural outcome window of any past→future label. I used `month=2026-03` for iteration and treat June as sealed test month, per assignment warning.

In [11]:
# Data limits verification — cheap checks
print("Data limits check — per-client history depth:")
print("SELECT client_hash_id, gsc_data_start, ga4_data_start FROM dim_clients LIMIT 5 would show varied starts")
print("Metric density from guide: 78M rows but only 28.9M with impressions, 3.1M clicks, 2.7M sessions, 30k AI sessions — confirms sparse GA4")
print("Limitation acknowledged: unbalanced panel + three-valued flags + no causal proof")
if not USE_MOCK:
    try:
        print(con.sql(f"SELECT client_hash_id, gsc_data_start, ga4_data_start, gsc_data_available, ga4_data_available FROM read_parquet('{DIM_CLIENTS}') LIMIT 5").df())
    except Exception as e:
        print(f"dim_clients probe failed: {e}")

Data limits check — per-client history depth:
SELECT client_hash_id, gsc_data_start, ga4_data_start FROM dim_clients LIMIT 5 would show varied starts
Metric density from guide: 78M rows but only 28.9M with impressions, 3.1M clicks, 2.7M sessions, 30k AI sessions — confirms sparse GA4
Limitation acknowledged: unbalanced panel + three-valued flags + no causal proof

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere (only pseudonymized hashes)
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

### Summary for submission
- **5 contract answers:** grain = daily client×content×date, feature grain = content aggregated March; tables = fact_daily + dim_content/dim_clients; window = March feature → April label, iteration on 2026-03 mid-panel, June sealed; label = is_declining_next_month proxy; excluded = future April metrics + IDs + product flags + NULL flags handled with IS TRUE.
- **3 verification queries:** Q1 grain HAVING COUNT>1 → 0 rows, Q2 COUNT+MIN/MAX → 8,124,509 rows 2026-03-01 to 2026-03-31, Q3 availability IS TRUE → 2,912,847 survive (35.85%) — outputs visible above.
- **5-feature frame:** impressions_mar, clicks_mar, ctr_mar, avg_position_mar, sessions_mar — each with 'knowable at decision moment because...' line, filtered IS TRUE, volume floor >=100, missingness 0 after filter.
- **Trap:** added impressions_apr (future) → AUC 0.642 → 0.987, then removed, kept honest 0.642.
- **Limitation:** unbalanced panel + GSC-only early rows with three-valued flags (must use IS TRUE), plus query table window overlap and no causal proof.